"""teste

Revision ID: 73a4e9aff6e7
Revises: 
Create Date: 2025-04-26 06:26:22.400692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73a4e9aff6e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('source_org_id', sa.UUID(), nullable=False),
    sa.Column('destination_org_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='importstatus'), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('callback_url', sa.String(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_audited', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfer_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False, comment='ID of the medical record being transferred'),
    sa.Column('source_org_id', sa.UUID(), nullable=False, comment='Source healthcare organization ID'),
    sa.Column('destination_org_id', sa.UUID(), nullable=False, comment='Destination healthcare organization ID'),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'VERIFIED', name='transferstatus'), server_default='pending', nullable=False, comment='Current status of the transfer'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when transfer was initiated'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when transfer was last updated'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when transfer was completed'),
    sa.Column('parameters', sa.JSON(), server_default='{}', nullable=False, comment='Configuration parameters for the transfer'),
    sa.Column('error_details', sa.JSON(), nullable=True, comment='Error details if transfer failed'),
    sa.Column('audit_log', sa.JSON(), nullable=True, comment='Complete audit trail for compliance'),
    sa.PrimaryKeyConstraint('id'),
    comment='Audit log for medical record transfers between organizations'
    )
    op.create_index(op.f('ix_transfer_logs_id'), 'transfer_logs', ['id'], unique=False)
    op.create_index(op.f('ix_transfer_logs_record_id'), 'transfer_logs', ['record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_logs_record_id'), table_name='transfer_logs')
    op.drop_index(op.f('ix_transfer_logs_id'), table_name='transfer_logs')
    op.drop_table('transfer_logs')
    op.drop_table('import_jobs')
    # ### end Alembic commands ###
